# test-2 scaled dot product attention

## softmax

In [2]:
from typing import Optional

import torch
import torch.nn as nn

In [3]:
def softmax(x: torch.Tensor, dim: int, subtract_max: bool = True) -> torch.Tensor:
    '''
    Use the trick of subtracting the maximum value in
    the i-th dimension from all elements of the i-th dimension to avoid numerical stability issues.
    '''
    x_max = x.max(dim=dim, keepdim=True).values
    if subtract_max:
        x_ = x - x_max
    else:
        x_ = x
    x_exp = torch.exp(x_)
    x_exp_sum = x_exp.sum(dim=-1, keepdim=True)#.unsqueeze(-1)
    x_exp = x_exp/x_exp_sum
    return x_exp
    


In [4]:
x = torch.randn(2, 4)
softmax(x, dim=1)

tensor([[0.0884, 0.5213, 0.0540, 0.3364],
        [0.3211, 0.1046, 0.2795, 0.2949]])

In [5]:
# test 'softmax operation is invariant to adding any constant c to all inputs'ArithmeticError
out1 = softmax(x, dim=1, subtract_max=True)
out2 = softmax(x, dim=1, subtract_max=False)

In [6]:
print(out1[0])
print(out2[0])

tensor([0.0884, 0.5213, 0.0540, 0.3364])
tensor([0.0884, 0.5213, 0.0540, 0.3364])
