In [1]:
import numpy as np
import torch
import numpy.typing as npt

In [5]:
seq_len = 32
x = np.random.randint(0, 1000,size=(seq_len))
print(x.shape)

(32,)


In [7]:
context_length = 16
batch_size = 8
start_idxs = np.random.randint(0, seq_len - context_length, size=(batch_size,))

In [8]:
start_idxs

array([ 8, 14,  7, 11,  3,  7, 13,  0])

In [11]:
start_idxs[:, np.newaxis]

array([[ 8],
       [14],
       [ 7],
       [11],
       [ 3],
       [ 7],
       [13],
       [ 0]])

In [ ]:
# indexing 방법
indices = start_idxs[:, np.newaxis] + np.arange(context_length)

In [10]:
indices

array([[ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [12]:
batch_input_ids = x[indices]

In [13]:
batch_input_ids

array([[610, 394, 988, 743, 597, 714,  86, 497, 930, 513,   8, 406,  90,
        819, 721,  85],
       [ 86, 497, 930, 513,   8, 406,  90, 819, 721,  85, 535, 768, 411,
        109, 595, 195],
       [362, 610, 394, 988, 743, 597, 714,  86, 497, 930, 513,   8, 406,
         90, 819, 721],
       [743, 597, 714,  86, 497, 930, 513,   8, 406,  90, 819, 721,  85,
        535, 768, 411],
       [134, 202, 180, 277, 362, 610, 394, 988, 743, 597, 714,  86, 497,
        930, 513,   8],
       [362, 610, 394, 988, 743, 597, 714,  86, 497, 930, 513,   8, 406,
         90, 819, 721],
       [714,  86, 497, 930, 513,   8, 406,  90, 819, 721,  85, 535, 768,
        411, 109, 595],
       [274, 864, 958, 134, 202, 180, 277, 362, 610, 394, 988, 743, 597,
        714,  86, 497]])